### ISSUE TITLE
[提醒]应遵照源项目开源协议Apache License 2.0，注明使用了tachiyomi的源码，并带有License

### ISSUE THREAD

**Issue by zhongfly** [Haleydu/Du#2]
显而易见，这个app完全基于tachiyomi及其插件，按照开源协议，应该注明使用了tachiyomi的源码，并附带有它的Apache License。
目前我在app中以及此项目仓库中尚未见到这些，我想大概是您忘记添加了吧。
https://github.com/tachiyomiorg/tachiyomi/blob/master/LICENSE

**Comment by Haleydu** [comment]
抱歉，最近实在没什么时间打理github仓库，很多细节的地方没有注意。会慢慢完善
